import { StyleSheet, Text, View } from "react-native";

const chanceListstyles = StyleSheet.create({
  roundButton1: {
    width: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
    // padding: 10,
    borderRadius: 100,
    backgroundColor: "#1F3842",
  },
  investBtn: {
    width: 30,
    height: 30,
    backgroundColor: "white",
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 5,
    marginVertical: 5,
  },
  investBtnSelected: {
    width: 30,
    height: 30,
    backgroundColor: "#009943",
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 5,
    shadowColor: "yellow",
    shadowOffset: { width: 7, height: 7 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 4,
    marginVertical: 5,
  },
  fillFormCardSize: {
    backgroundColor: "white",
    width: 25,
    height: 25,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 7,
    marginHorizontal: 2,
  },
  investNumBox: {
    borderColor: "white",
    borderRadius: 7,
    borderWidth: 1,
    width: "95%",
    height: 140,
    alignSelf: "center",
    marginTop: 20,
    padding: 10,
  },
});
export default chanceListstyles;
